server:
  port: 8000
spring:
  application:
    name: gateway-server
  # 注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 172.24.108.245:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: oauth-server
          uri: lb://oauth-server
          predicates:
            - Path=/oauth-server/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://127.0.0.1:8001/oauth-server/rsa/publicKey' # 获取JWT验签公钥请求路径

  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 172.24.108.246
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 10000ms
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0


logging:
  level:
    org.springframework: info
    com.yht.oauth2: debug

secure:
  ignore:
    urls: #配置白名单路径
      - "/swagger-ui.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/oauth2-server/login/**"
      - "/oauth2-server/oauth/token"
      - "/oauth2-server/rsa/publicKey"
      - "/oauth2-server/oauth/authorize"
